### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by cristianuibar** [webfactor/laravel-backpack-instant-fields#12]
## Detailed description

The searching in the ajax field is not working as expected. Not sure why. Used this package before when it was in alpha I guess and I loved it. Now I have quite a few issues with it. Starting from the fact that the Cancel button on the modal doesn't work, only if you press somewhere outside the modal it closes, to the fact that the search is not working. 

Here is a video showing my problem:
https://buffup.fleeq.io/l/q4iu1dti6y-nb1xx47m2b?ap=1

## Context

No change. It's the basic functionality.

## Possible implementation

Not sure. I was unable to pinpoint the specific problem yet.

## Your environment

Localhost testing end:
XAMPP with PHP 7.2 Maria DB 10.2 and L5.6 with latest backpack version.

**Comment by tswonke** [comment]
Hi @cristianuibar 

Thank you for the video. I'm not sure what is wrong with the "cancel" button :-/
I use the latest version in my projects and they work.

About the Request:

Sorry for this beeing confusing, but I didn't come up with a better solution, because it's tricky to access infos from one CrudController in another.

The standard way is to omit the `data-source`. It will point to `$crud->getRoute().'/ajax'` of the controller where you define your fields. The index method gets the name of the field and can now access the model that is defined in your field!

So the search will not be performed on `.../customer/ajax` but on `.../yourCrud/ajax`.
Create and store will be performed on `.../customer/ajax`.

That's the reason why you need the trait and routes for both cruds. Or you implement your on search.
